#!/usr/bin/env python

import lib
import sys, re, os, textwrap
from optparse import OptionParser

parser = OptionParser()
(options, args) = parser.parse_args()

if len(args) < 2:
  sys.exit(1)

if args[0] == "-":
  inlines = sys.stdin.read()
else:
  try:
    inlines = open(args[0], "r").read()
  except:
    sys.exit(1)

if args[1] == "-":
  outfile = sys.stdout
else:
  try:
    outfile = open(args[1], "w")
  except:
    sys.exit(1)

print >>outfile, lib.clean(inlines)
