START = noxxxnote
END = missing
CLASS = $(PYTEX)/cls/nsfcnsproposal.cls

all: geoffreychallen-separate template-separate

# 16 Nov 2010 : GWA : Add other cleaning rules here.

clean: rulesclean

include $(PYTEX)/make/Makerules
